dense_embedding:
  package: "fastembed"
  model_name: "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
  params:
    size: 768
    distance: "Cosine"
    on_disk: true

sparse_embedding:
  package: "fastembed"
  model_name: "Qdrant/bm25"
  params: {}

late_interaction_embedding:
  package: "fastembed"
  model_name: "answerdotai/answerai-colbert-small-v1"
  params:
    size: 96
    distance: "Cosine"
    on_disk: true
    multivector_config:
      comparator: "MAX_SIM"

# --- General Pipeline Settings ---
multi_tenant: false
replication_factor: 1
shard_number: 3